version: 2

updates:
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      time: '08:30'
      timezone: 'Asia/Shanghai'
    reviewers:
      - everyx
    assignees:
      - everyx
    commit-message:
      prefix: ci
      include: scope

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: monthly
      time: '08:30'
      timezone: 'Asia/Shanghai'
    reviewers:
      - everyx
    assignees:
      - everyx
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
