version: "3"

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:8
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports: 
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  backup:
    image: everyx/mysql-backup
    depends_on: 
      - mysql
    build: 
      context: .
      args:
        - http_proxy
        - https_proxy
    environment: 
      - http_proxy
      - https_proxy
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASES=${MYSQL_DATABASE}
      - RCLONE_DEST=${RCLONE_DEST}
    volumes: 
      - ./rclone.conf:/rclone.conf
