name: Docker Image

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - '.*'
      - '*.md'
      - 'docker-compose.yml'
      - 'Makefile'
      - '.github/*.yml'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: everyx/mysql-backup
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Registry
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
